### ISSUE TITLE
RAK2287 on RPI4 (hotspot v2)

### ISSUE THREAD

**Issue by ccall48** [RAKWireless/udp-packet-forwarder#17]
Setting up a hotspot v2 using the udp-packet-forwarder it seems to select and use the right concentrator after a complete power cycle, but if i pull the container down or reboot the machine without a full power cycle on every restart it seems to pick the wrong concentrator and throws and error about being the wrong reset pin. It throws that same error when it initialises on the first try but the dynamic select seems to fix the problem.

I have put the logs here as to not flood github too much.

https://pastebin.com/FNU4KDNg

**Comment by ccall48** [comment]
Here is an example of my compose in case you see anything wrong here.

```yml
services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      MODEL: 'RAK2287'
      GATEWAY_EUI: 'D83ADDFF........'
      BAND: 'au_915_928' # AU915_SB2
      DEVICE: '/dev/spidev0.0'
      RADIO_DEV: '/dev/ttyACM0'
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: 1800
```

**Comment by ccall48** [comment]
I dropped back a version of debian to test and was still having the same problem.
I ended up playing with the compose - not sure exactly what the difference is but this managed to accept the reset pin on 25 and it seems to be working every time between restarts and reboots etc.

```yml
services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: 'RAK2287'
      BAND: 'au_915_928'
      DEVICE: '/dev/spidev0.0'
      RESET_GPIO: 25
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: 1800
```

**Comment by xoseperez** [comment]
Hi @ccall48 
The RESET_GPIO by default is 17 (and you were receiving errors on that: `Warning: /sys/class/gpio/gpio17 does not exist`). Once you set it to the right value then it worked. 
Also, you were using `RADIO_DEV` on your first version which is deprecated but takes precedence over `RADIO` setting for backwards compatibility. you seconds version fixes that too removing that setting.

**Comment by ccall48** [comment]
That was also the port it picked when on auto provision, is it worth reporting that?

I assume it never acknowledged the gpio reset port because i was using a depreciated env var?

Thanks for replying, i have no doubt it was something i did 😂

**Comment by ccall48** [comment]
Just tried on another gateway (bookworm base where the inital problem started) and it still appears.

container setup.
```yml
services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: 'RAK2287'
      BAND: 'au_915_928'
      DEVICE: '/dev/spidev0.0'
      RESET_GPIO: 25
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: 1800
      GPS_LATITUDE: -31.12423
      GPS_LONGITUDE: 150.90999
      GPS_ALTITUDE: 420
```

https://pastebin.com/nVT4ETvv

worked on first pull up, then fails to start on subsequent container down and restarts. after as it says gpi 25 doesnt exist, i will persist for a little while then try dropping debian version again.
