### ISSUE TITLE
Auto Provision ChirpStack Gateway not working

### ISSUE THREAD

**Issue by CoenraadS** [RAKWireless/udp-packet-forwarder#18]
I am using the default ChirpStack compose file from: https://github.com/chirpstack/chirpstack-docker/blob/master/docker-compose.yml

My additions:

```
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    privileged: true
    depends_on:
      - chirpstack-gateway-bridge
    environment:
      MODEL: "RAK7371"
      INTERFACE: "USB"
      DEVICE: "/dev/ttyACM0"
      BAND: au_915_928
      GATEWAY_EUI_SOURCE: chip
      SERVER_HOST: chirpstack-gateway-bridge
      CS_TENANT_ID: "XXXX-XXXX-XXXX..."
      CS_TOKEN: "eyJ0eXXXXXXXXXX..."
      CS_API_URL: "chirpstack-rest-api:8090"
```

If I manually define the `RAK7371` Gateway in ChirpStack is is detected, but I would expect it to be automatically created on startup.
